### ISSUE TITLE
Unable to Install Kvmtop On kvm-server

### ISSUE THREAD

**Issue by MohamedHz** [cha87de/kvmtop#1]
Hi,

Thanks for posting the wonderfull document but I am unable to install the kvmtop binary on my kvm server and facing an error which mentioned below:

I have refered many forums but i could not get an proper solution to fix the issue. Hope there is an proper solution to fix this.
## Error

[root@kvm kvmtop]# go install github.com/cha87de/kvmtop
# github.com/rthornton128/goncurses

/tmp/go-build971672263/github.com/rthornton128/goncurses/_obj/goncurses.o: In function `ncurses_is_subwin':
src/github.com/rthornton128/goncurses/goncurses.c:71: undefined reference to`is_subwin'
/tmp/go-build971672263/github.com/rthornton128/goncurses/_obj/goncurses.o: In function `ncurses_is_pad':
src/github.com/rthornton128/goncurses/goncurses.c:63: undefined reference to`is_pad'
collect2: ld returned 1 exit status

**Comment by cha87de** [comment]
Hi, 
thank you for your interest in kvmtop. I will look into this issue asap. From the error messages I assume that somehow changes in the git repo github.com/rthornton128/goncurses are breaking the build.
As a work around you can use the x86-64 binary build from the github releases here https://github.com/cha87de/kvmtop/releases
All the best
Christopher

**Comment by MohamedHz** [comment]
Hi Christopher..Thanks for your reply. But still I am facing the same issue on the next release too.. Could you please help me to resolve the issue. The Binary file was working fine...

**Comment by cha87de** [comment]
Hi Mohamed,
I tried to reproduce the error you get. Unfortunately I failed, since this works for me:

```
$ cd /tmp/
$ mkdir kvmtop && cd kvmtop
$ export GOPATH=`pwd`
$ go get "github.com/cha87de/kvmtop"
$ go install github.com/cha87de/kvmtop
$ ./bin/kvmtop 
```

Also the travis build server for kvmtop [1] works fine. Can you please provide more details about your setup, since i cannot find any issues? e.g. which version and which compiler of go do you use?

Thanks a lot
Christopher

[1] https://travis-ci.org/cha87de/kvmtop
