### ISSUE TITLE
json printer generates invalid json string

### ISSUE THREAD

**Issue by rsu-gmbh** [cha87de/kvmtop#14]
Using version 2.0.1

`kvmtop --cpu --printer=json -r1`

generates a json string with commas at the end of each object/array

`[{"UUID": "655a9721-93c0-4d12-9c25-02de775ac863","name": "test","cpu_cores": "4","cpu_total": "","cpu_steal": "","cpu_other_total": "","cpu_other_steal": "",},]`

**Comment by cha87de** [comment]
Should be fixed with commit 75b4328d10f8fec7b562783ea774faffe4adf8d8 which is included in release 2.0.1 - but you will then probably run into issue #12 :-(

**Comment by analistamarcioprado** [comment]
I have the same problem.

Only from the 3 query does the cpu_total appear.

I am using the version: 2.0.1

#kvmtop --cpu --printer=json -r1
[]
[{"UUID": "ad3dfd25-a429-4e9a-80a7-c8d88169ca47","name": "Windows7","cpu_cores": "1","cpu_total": "","cpu_steal": "","cpu_other_total": "","cpu_other_steal": "",},]


#kvmtop --cpu --printer=json -r3
[]
[{"UUID": "ad3dfd25-a429-4e9a-80a7-c8d88169ca47","name": "Windows7","cpu_cores": "1","cpu_total": "","cpu_steal": "","cpu_other_total": "","cpu_other_steal": "",},]
[{"UUID": "ad3dfd25-a429-4e9a-80a7-c8d88169ca47","name": "Windows7","cpu_cores": "1","cpu_total": "","cpu_steal": "","cpu_other_total": "","cpu_other_steal": "",},]
[{"UUID": "ad3dfd25-a429-4e9a-80a7-c8d88169ca47","name": "Windows7","cpu_cores": "1",**"cpu_total": "1"**,"cpu_steal": "0","cpu_other_total": "3","cpu_other_steal": "0",},]

**Comment by cha87de** [comment]
@analistamarcioprado I opened a new issue with the empty field problem in #17

The invalid comma issue will be fixed in the upcoming release.

**Comment by cha87de** [comment]
@rsu-gmbh @analistamarcioprado the new release 2.1 [1] is ready - could you please check if the json is now valid in your setups? thanks in advance for your support!

[1] https://github.com/cha87de/kvmtop/releases/tag/2.1
