### ISSUE TITLE
Flag output unknown

### ISSUE THREAD

**Issue by analistamarcioprado** [cha87de/kvmtop#16]
Flag output unknown in kvmtop version 2.0.1

kvmtop --cpu --printer = json --output = tcp --target = 127.0.0.1: 12345
unknown flag `output '

Am I doing something wrong?

**Comment by cha87de** [comment]
Hi @analistamarcioprado 

the support for different output options including tcp are available on the master branch only.
The options for v2.0.1 are listed here: https://github.com/cha87de/kvmtop/blob/2.0.1/README.md#usage

The build of the master branch is available as docker image `cha87de/kvmtop:master`. I will finish remaining open issues on the master branch and will come up with a new release.

Sorry for the confusion!

**Comment by cha87de** [comment]
Dear @analistamarcioprado , the requested flags are now part of the new release 2.1. You can download the deb/rpm packages or the binary [https://github.com/cha87de/kvmtop/releases/tag/2.1](here) or use the docker image [https://hub.docker.com/r/cha87de/kvmtop/](cha87de/kvmtop:latest). If you have any further issues, please let me know! Muito obrigado

**Comment by analistamarcioprado** [comment]
How cool, thank you for the explanations. Vielen Dank!
