### ISSUE TITLE
kvmtop ncurses printer error when running without any collector

### ISSUE THREAD

**Issue by MyungChi** [cha87de/kvmtop#18]
Hi.

I install kvmtop rpm on my host.

When I execute it has shown error, It doesn't work properly.
 
$ kvmtop

 panic: runtime error: index out of range

                                         goroutine 9 [running]:
                                                               github.com/cha87de/kvmtop/printers.sortDomainIDsByField(0xc4201e0000, 0x3, 0x0, 0x0, 0x1)
                                                                /home/travis/gopath/src/github.com/cha87de/kvmtop/printers/ncurses.go:185 +0x2cd
                                                 github.com/cha87de/kvmtop/printers.printDomain(0xc4201e6010, 0xc4201de000, 0x2, 0x2, 0xc4201e0000, 0x3)
                                                                /home/travis/gopath/src/github.com/cha87de/kvmtop/printers/ncurses.go:161 +0x597
                                                 github.com/cha87de/kvmtop/printers.(*NcursesPrinter).Screen(0xc4200116c0, 0x0, 0x0, 0x0, 0xc4201de000, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
                                                                                        /home/travis/gopath/src/github.com/cha87de/kvmtop/printers/ncurses.go:61 +0x17c
                                                                        github.com/cha87de/kvmtop/runners.handleRun()
                        /home/travis/gopath/src/github.com/cha87de/kvmtop/runners/printer.go:74 +0x869
       github.com/cha87de/kvmtop/runners.initializePrinter(0xc420015cd0)
                                                                                /home/travis/gopath/src/github.com/cha87de/kvmtop/runners/printer.go:27 +0x88
                                                              created by github.com/cha87de/kvmtop/runners.InitializeRunners
                                /home/travis/gopath/src/github.com/cha87de/kvmtop/runners/runners.go:15 +0xb3

**Comment by cha87de** [comment]
Hi @MyungChi ,
thanks for reporting. The issue is, that no metric collector is chosen, can you please try to run the command again with e.g. `kvmtop --cpu`? For more metrics please visit https://github.com/cha87de/kvmtop/blob/2.1/README.md#collectors--their-fields

Of course the usability of kvmtop is broken here: at least one default collector should be enabled, and the ncurses printer should obviously not break if no collector is seleted.

**Comment by MyungChi** [comment]
> Hi @MyungChi ,
> thanks for reporting. The issue is, that no metric collector is chosen, can you please try to run the command again with e.g. `kvmtop --cpu`? For more metrics please visit https://github.com/cha87de/kvmtop/blob/2.1/README.md#collectors--their-fields
> 
> Of course the usability of kvmtop is broken here: at least one default collector should be enabled, and the ncurses printer should obviously not break if no collector is seleted.

Thanks for your quick response. I will try with some metric. 
But, I think that it would be better to apply default metric instead of error.

**Comment by MyungChi** [comment]
Hi.

I have two issues in kvmtop.

<del>
**1. Exception --disk** 

When I add metric collector "--disk", It has shown below error.
Without "--disk" option, It is working fine.

$ kvmtop -c qemu:///system --printer json --cpu --mem --disk --net -f 1 --output=tcp --target=127.0.0.1:8343
Output will be redirected to tcp://127.0.0.1:8343
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x723601]

goroutine 18 [running]:
github.com/cha87de/kvmtop/collectors/diskcollector.diskLookup(0xc42023bb10, 0x7efc20000b20)
        /home/travis/gopath/src/github.com/cha87de/kvmtop/collectors/diskcollector/worker.go:112 +0x311
github.com/cha87de/kvmtop/collectors/diskcollector.(*Collector).Lookup.func1(0x8048c0, 0xc42014c540, 0x8682c0, 0xc420075770, 0x24)
        /home/travis/gopath/src/github.com/cha87de/kvmtop/collectors/diskcollector/collector.go:25 +0x11d
sync.(*Map).Range(0xc92a68, 0xc42023bcc0)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/sync/map.go:336 +0x150
github.com/cha87de/kvmtop/collectors/diskcollector.(*Collector).Lookup(0xc42003f780)
        /home/travis/gopath/src/github.com/cha87de/kvmtop/collectors/diskcollector/collector.go:20 +0x71
github.com/cha87de/kvmtop/runners.lookup.func2(0x8048c0, 0xc42003f790, 0x830680, 0xc42003f780, 0x804801)
        /home/travis/gopath/src/github.com/cha87de/kvmtop/runners/lookup.go:65 +0x55
sync.(*Map).Range(0xc92a90, 0x89da60)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/sync/map.go:336 +0x150
github.com/cha87de/kvmtop/runners.lookup()
        /home/travis/gopath/src/github.com/cha87de/kvmtop/runners/lookup.go:63 +0x363
github.com/cha87de/kvmtop/runners.initializeLookup(0xc4200d0000)
        /home/travis/gopath/src/github.com/cha87de/kvmtop/runners/lookup.go:21 +0x54
created by github.com/cha87de/kvmtop/runners.InitializeRunners
        /home/travis/gopath/src/github.com/cha87de/kvmtop/runners/runners.go:13 +0x6f

</del>

issue #19 

<del>
**2. Data is not collect**

When I set "-f 60" It report as below.  I generate traffic almost 50% on "mepm VM" 

This is default frequency( maybe 1 secs)
**$  kvmtop -c qemu:///system --printer json --cpu --mem --net**
{
	"host": {
		"cpu_cores": 4,
		"cpu_meanfreq": 2323.987976,
		"ram_Total": 8081032,
		"ram_Free": 471884,
		"ram_Available": 2292192,
		"net_host_receivedBytes": 0,
		"net_host_transmittedBytes": 0
	},
	"domains": [{
			"UUID": "2f21bf30-baa9-49ef-ad0a-915ed281a3bb",
			"name": "centos7.0",
			"cpu_cores": 2,
			"cpu_total": 0,
			"cpu_steal": 0,
			"ram_total": 2952772,
			"ram_used": 141676,
			"net_receivedBytes": 0,
			"net_transmittedBytes": 52
		}, {
			"UUID": "eb40b9d1-87e6-455d-a6b4-b27229c9652c",
			"name": "mepm",
			"cpu_cores": 2,
			**"cpu_total": 50,**
			"cpu_steal": 0,
			"ram_total": 2952772,
			"ram_used": 128508,
			"net_receivedBytes": 0,
			"net_transmittedBytes": 52
		}
	]
}

Below one is set to "-f 60"
**$ kvmtop -c qemu:///system --printer json --cpu --mem --net -f 60**
{
		"host": {
			"cpu_cores": 4,
			"cpu_meanfreq": 2299.977478,
			"ram_Total": 8081032,
			"ram_Free": 1483408,
			"ram_Available": 2504672,
			"net_host_receivedBytes": 6028,
			"net_host_transmittedBytes": 1940
		},
		"domains": [{
				"UUID": "2f21bf30-baa9-49ef-ad0a-915ed281a3bb",
				"name": "centos7.0",
				"cpu_cores": 2,
				**"cpu_total": 237,**
				"cpu_steal": 1,
				"ram_total": 2952772,
				"ram_used": 141676,
				"net_receivedBytes": 0,
				"net_transmittedBytes": 26
			}, {
				"UUID": "eb40b9d1-87e6-455d-a6b4-b27229c9652c",
				"name": "mepm",
				"cpu_cores": 2,
				**"cpu_total": 183219,**
				"cpu_steal": 55,
				"ram_total": 2952772,
				"ram_used": 128508,
				"net_receivedBytes": 6172,
				"net_transmittedBytes": 1970
			}
		]
	}

Do I need any calculation when I set "-f" ?

</del>

issue #20

**Comment by cha87de** [comment]
Thanks @MyungChi  for the  bug reports. I will incorporate fixes for the bugs you found.

**Comment by cha87de** [comment]
bf97094 fixes the ncurses printer, still a set of default collectors should be enabled when no collectors are given.
