### ISSUE TITLE
CPU utilization for VM is not collect when I set "-f 60"

### ISSUE THREAD

**Issue by MyungChi** [cha87de/kvmtop#20]
Hi. 

I want to collect KVM status periodically( every 1 min ).

When I set "-f 60" It report as below. I generate traffic with stress tool almost 50% on "guest VM"
Is kvmtop didn't collect CPU utilization ? 

If possible, I want to ask to add CPU utilization(/proc/stat) , UUID(dmidecode -s system-uuid) and name for HOST OS. It would be very helpful to me.

This is default frequency( maybe 1 secs)
$ kvmtop -c qemu:///system --printer json --cpu --mem --net
{
"host": {
"cpu_cores": 4,
"cpu_meanfreq": 2323.987976,
"ram_Total": 8081032,
"ram_Free": 471884,
"ram_Available": 2292192,
"net_host_receivedBytes": 0,
"net_host_transmittedBytes": 0
},
"domains": [{
"UUID": "2f21bf30-baa9-49ef-ad0a-915ed281a3bb",
"name": "centos7.0",
"cpu_cores": 2,
"cpu_total": 0,
"cpu_steal": 0,
"ram_total": 2952772,
"ram_used": 141676,
"net_receivedBytes": 0,
"net_transmittedBytes": 52
}, {
"UUID": "eb40b9d1-87e6-455d-a6b4-b27229c9652c",
"name": "mepm",
"cpu_cores": 2,
"cpu_total": 50,
"cpu_steal": 0,
"ram_total": 2952772,
"ram_used": 128508,
"net_receivedBytes": 0,
"net_transmittedBytes": 52
}
]
}

Below one is set to "-f 60"
$ kvmtop -c qemu:///system --printer json --cpu --mem --net -f 60
{
"host": {
"cpu_cores": 4,
"cpu_meanfreq": 2299.977478,
"ram_Total": 8081032,
"ram_Free": 1483408,
"ram_Available": 2504672,
"net_host_receivedBytes": 6028,
"net_host_transmittedBytes": 1940
},
"domains": [{
"UUID": "2f21bf30-baa9-49ef-ad0a-915ed281a3bb",
"name": "centos7.0",
"cpu_cores": 2,
"cpu_total": 237,
"cpu_steal": 1,
"ram_total": 2952772,
"ram_used": 141676,
"net_receivedBytes": 0,
"net_transmittedBytes": 26
}, {
"UUID": "eb40b9d1-87e6-455d-a6b4-b27229c9652c",
"name": "mepm",
"cpu_cores": 2,
"cpu_total": 183219,
"cpu_steal": 55,
"ram_total": 2952772,
"ram_used": 128508,
"net_receivedBytes": 6172,
"net_transmittedBytes": 1970
}
]
}

Do I need any calculation when I set "-f" ?

**Comment by cha87de** [comment]
Probably an error in the time diff at https://github.com/cha87de/kvmtop/blob/master/collectors/cpucollector/worker.go#L133
More detailed debugging needed.. Thanks for reporting

**Comment by cha87de** [comment]
The issue with changing the frequency is fixed in the new release 2.1.1.  The CPU utilization should now be reported accurately. Can you please confirm that this works now?

Regarding the host where kvmtop is running: please us the `--host` collector, which provides the hostname as an additional metric.
