### ISSUE TITLE
When TCP connection loss, Process is terminated. 

### ISSUE THREAD

**Issue by MyungChi** [cha87de/kvmtop#25]
kvmtop output set to TCP(to logstash), when I restart logstash, kvmtop is lost tcp connection and terminate process. It would be good to retry TCP connection when logstash is  alive.

When kvmtop is working on system service, TCP connection retry shall be required.

**Comment by cha87de** [comment]
This behaviour is on purpose and intended, following a "fail fast and retry" logic of cloud computing / containers. Please use a container or a systemd unit to automatically restart kvmtop. That should lead to the same feature.

**Comment by MyungChi** [comment]
Thanks for your guide. I set restart option on systemd unit.
