### ISSUE TITLE
Host memory is not collected.

### ISSUE THREAD

**Issue by MyungChi** [cha87de/kvmtop#28]
Hi. 

I set new machine in lab env. There are no active VM in KVM. At that time ram information for Host is not collected.

$  kvmtop --cpu --mem --printer=json 
{ "host": {"ram_Total": "","ram_Free": "","ram_Available": "","cpu_cores": 10,"cpu_curfreq": 0.000000}, "domains": []}
{ "host": {"ram_Total": "","ram_Free": "","ram_Available": "","cpu_cores": 10,"cpu_curfreq": 0.000000}, "domains": []}
{ "host": {"ram_Total": "","ram_Free": "","ram_Available": "","cpu_cores": 10,"cpu_curfreq": 0.000000}, "domains": []}
{ "host": {"ram_Total": "","ram_Free": "","ram_Available": "","cpu_cores": 10,"cpu_curfreq": 0.000000}, "domains": []}
{ "host": {"ram_Total": "","ram_Free": "","ram_Available": "","cpu_cores": 10,"cpu_curfreq": 0.000000}, "domains": []}
{ "host": {"ram_Total": "","ram_Free": "","ram_Available": "","cpu_cores": 10,"cpu_curfreq": 0.000000}, "domains": []}
{ "host": {"ram_Total": "","ram_Free": "","ram_Available": "","cpu_cores": 10,"cpu_curfreq": 0.000000}, "domains": []}

If I check with virsh command, result is as below.

# virsh nodememstats 
total  :            197639624 KiB
free   :            124508044 KiB
buffers:                 2136 KiB
cached :             53727560 KiB

**Comment by cha87de** [comment]
Thanks for reporting, @MyungChi . 
so the host memory measurements are not available (only) when the host has no VMs?

**Comment by MyungChi** [comment]
Yes, host has VM, mem info is collected.

**Comment by MyungChi** [comment]
Do U need any other extra info.?

**Comment by cha87de** [comment]
i didn't had the time to look into that issue yet. since i'm not paid for kvmtop so what is needed is spare time or even better a fix for the problem :-)

**Comment by igalvarez** [comment]
Hi, dont know if my issue is the same, but I'm unabled to collect mem. See image atached. Let me know if you need some other info. 👍 
![kvmtop mem](https://user-images.githubusercontent.com/27913191/56490913-168be280-64e7-11e9-8cf5-4d33078e3630.PNG)

Thanks

**Comment by cha87de** [comment]
Hi @igalvarez 
can you please check if you have the qemu guest agent installed on those VMs which have memory reported, and that this agent is missing on the other VMs?
If this is the case, your issue is related to #27 .
Thanks!

**Comment by cha87de** [comment]
@MyungChi The bug you described is related to the fact, that the kvmtop collectors' `Collect` method is only called then there are VMs .. This has to be fixed for host metrics.
