### ISSUE TITLE
Memory info. is not collected correctly.

### ISSUE THREAD

**Issue by MyungChi** [cha87de/kvmtop#29]
I start/stop kvmtop several time to verify it after check out source code and build kvmtop binary by myself.

As you see below. memory info. is not collected sometimes.

 ```
./kvmtop 
 eb40b9d1 mepm     2     0     0     2952772 137456

 cpu                ram              
 cores    4         Total
 curfreq  0.000000  Free
                    Availabl 

                   cpu               ram
 UUID     name     cores total steal total   used   
 dc5389f4 redmine- 2     0     0     2047556 101200
 eb40b9d1 mepm     2     0     0     2952772 137456
 914469ff openapig 2     0     0     2952772 133192
 42de0be1 svcrepo  2     0     0     2952772 137304
```

**Comment by cha87de** [comment]
Please clarify the relation between this new issue and issues #28 and #27. Thank you

**Comment by MyungChi** [comment]
This is not related issues #28 and #27.
#28 issue is not collected when no VM condition. It was occured when there are no VM in Host.
#27 issue is related qemu-guest-agent. mem info. is not collected when qemu agent is not installed on VM.

**Comment by cha87de** [comment]
Okay, thanks for clarifying this 😃

**Comment by cha87de** [comment]
@MyungChi this only happens for host memory, right? any further ideas when exactly this problem occurs?

**Comment by sunvim** [comment]
> This is not related issues #28 and #27.
> #28 issue is not collected when no VM condition. It was occured when there are no VM in Host.
> #27 issue is related qemu-guest-agent. mem info. is not collected when qemu agent is not installed on VM.

it seems to not correct where i install qemu agent in VM, can you tell me how to solve this, thanks
