### ISSUE TITLE
undefined: libvirt.Connect when running build command

### ISSUE THREAD

**Issue by gopherunner** [cha87de/kvmtop#34]
while trying to build for cross-platform I'm getting the following error msg:

**$ GO111MODULE=on GOOS=linux GOARCH=amd64 go build**
# github.com/cha87de/kvmtop/connector
../../connector/libvirt.go:12:17: undefined: libvirt.Connect
../../connector/libvirt.go:17:15: undefined: libvirt.NewConnect
# github.com/cha87de/kvmtop/models
../../models/libvirtDomains.go:15:62: undefined: libvirt.Domain
../../models/libvirtDomains.go:18:10: undefined: libvirt.Domain
../../models/libvirtDomains.go:20:21: undefined: libvirt.Domain
../../models/libvirtDomains.go:25:63: undefined: libvirt.Domain

any ideas?

**Comment by cha87de** [comment]
have you installed the libvirt-dev package on the host where you're building kvmtop?
Which linux distro do you use?

**Comment by gopherunner** [comment]
I’m running on a mac (trying to compile there), and trying to get the build
file to run a a linux amd64 server

**Comment by cha87de** [comment]
I've never tried to build it on a mac. please make sure to have the libvirt-dev tools installed correctly and maybe please check https://github.com/libvirt/libvirt-go for Mac OS support. Let me know if that's the right path to get it work :-)

**Comment by gopherunner** [comment]
also I´ve try to build it on ubuntu amd64 and also getting this error:

src/github.com/cha87de/kvmtop/cmd/kvmtop# go build
# pkg-config --cflags  -- ncurses form menu ncurses ncurses panel
Package ncurses was not found in the pkg-config search path.
Perhaps you should add the directory containing `ncurses.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ncurses' found
Package form was not found in the pkg-config search path.
Perhaps you should add the directory containing `form.pc'
to the PKG_CONFIG_PATH environment variable
No package 'form' found
Package menu was not found in the pkg-config search path.
Perhaps you should add the directory containing `menu.pc'
to the PKG_CONFIG_PATH environment variable
No package 'menu' found
Package ncurses was not found in the pkg-config search path.
Perhaps you should add the directory containing `ncurses.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ncurses' found
Package ncurses was not found in the pkg-config search path.
Perhaps you should add the directory containing `ncurses.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ncurses' found
Package panel was not found in the pkg-config search path.
Perhaps you should add the directory containing `panel.pc'
to the PKG_CONFIG_PATH environment variable
No package 'panel' found
pkg-config: exit status 1

libvirt-dev tools already installed.

**Comment by gopherunner** [comment]
got it :) was missing the following packages:
pkg-config libncurses5-dev

**Comment by gopherunner** [comment]
Thanks a lot! 👍

**Comment by cha87de** [comment]
yes, these dev packages are necessary. I will add it to the README since this documentation is obviously missing at the moment :-) thanks for pointing it out. looking forward  to extensions and pull requests :-)

**Comment by gopherunner** [comment]
I try many ways and still can't build it from macOS to linux amd64 :-(, I'm having the following error msg:

[gopherunner:...x/workspace/go/src]$ GOOS=linux GOARCH=amd64 go build github.com/cha87de/kvmtop/cmd/kvmtop 
# github.com/cha87de/kvmtop/connector
github.com/cha87de/kvmtop/connector/libvirt.go:12:17: undefined: libvirt.Connect
github.com/cha87de/kvmtop/connector/libvirt.go:17:15: undefined: libvirt.NewConnect
# github.com/cha87de/kvmtop/models
github.com/cha87de/kvmtop/models/libvirtDomains.go:15:62: undefined: libvirt.Domain
github.com/cha87de/kvmtop/models/libvirtDomains.go:18:10: undefined: libvirt.Domain
github.com/cha87de/kvmtop/models/libvirtDomains.go:20:21: undefined: libvirt.Domain
github.com/cha87de/kvmtop/models/libvirtDomains.go:25:63: undefined: libvirt.Domain

any ideas? I don't know why is not defined

**Comment by cha87de** [comment]
Hi @gopherunner 
could you please try a simple example snippet which uses the libvirt-go implementation? It's probably not a kvmtop issue but related to libvirt-go [1].
Please try the following:
```
package main

import (
	"fmt"

	libvirt "github.com/libvirt/libvirt-go"
)

func main() {
	uri := "qemu:///system"
	var connection *libvirt.Connect
	connection, _ = libvirt.NewConnect(uri)
	domains, _ := connection.ListAllDomains(libvirt.CONNECT_LIST_DOMAINS_ACTIVE)
	fmt.Printf("%+v", domains)
	defer connection.Close()
}
```
Thanks
[1] https://github.com/libvirt/libvirt-go

**Comment by gopherunner** [comment]
/libvirt-test]$ *GOOS=linux GOARCH=amd64 go build -v
github.com/test/libvirt-test <http://github.com/test/libvirt-test>*

github.com/test/libvirt-test
# github.com/test/libvirt-test
./main.go:11:18: undefined: libvirt.Connect
./main.go:12:18: undefined: libvirt.NewConnect
./main.go:13:42: undefined: libvirt.CONNECT_LIST_DOMAINS_ACTIVE

**Comment by cha87de** [comment]
In that case please ask the libvirt-go developers for support, since this is not related to kvmtop :-/

**Comment by gopherunner** [comment]
got it to work :), would be nice to have something like this:

[
 {
  "host_name": "host01",
  "instances": [
      {
         "UUID": "321433f-...-3339494d",
         "name": "instance-0000001",
         "status": "RUNNING",
         "statusTime": 15839393482
      },
      {
         ...
      }
   ],
  "capacity": {
       "total": {
           "disk": 737181,
           "mem": 256839,
           "cpus": 8
       },
       "used": {
            "disk": 102344,
            "mem": 128934,
            "cpus": 6
      }
   },
   "id": "01"
 }
]

is possible to have something like this? maybe creating a new `--all`
parameter, and also maybe some network info just in one

**Comment by cha87de** [comment]
good news that the build works with macos. what steps are required / which packets were required to install? if you could let me know, I will put it into the readme for other developers working with mac. 

regarding the json format, can you open a new issue for that?

thank you

**Comment by gopherunner** [comment]
Sure, just build with some flags:

*GOOS=linux GOARCH=amd64 go build -v -x -ldflags '-v -linkmode internal'
github.com/gopherunner/libvirt-go-test/test
<http://github.com/gopherunner/libvirt-go-test/test>*

also, install the following packages:

*pkg-config*
*libvirt*
*libvirt-dev*

on *libvirt* I had some problems with the link of the libraries but once
resolved it work fine.
