### ISSUE TITLE
How does CPU Virtual Machine Metrics: cpu_steal_time comes from

### ISSUE THREAD

**Issue by binjheBenjamin** [cha87de/kvmtop#40]
cpu_steal | internal metrics | stolen (reduced) cpu utilisation over all virtual CPU cores | collect

what is the exactly means of internal metrics , is it come from libvirt api? or other ways.

Thx.

**Comment by cha87de** [comment]
internal metrics means (stated on the very same site where you copied the broken table from):
> Metrics below the internal metrics sign are not exported but only available internally to process the exported metrics.

accordingly, cpu_steal is using such internal metrics as its source. cpu_times_${pid} and cpu_runqueues_${pid} to be exact. You can find the exact logic in the [cpucollector](https://github.com/cha87de/kvmtop/tree/69563835d52a4ea6794b007ae59b1370d612694d/collectors/cpucollector), meaning about the values from schedstat proc file in the [kernel docs](https://www.kernel.org/doc/html/latest/scheduler/sched-stats.html#proc-pid-schedstat).
