### ISSUE TITLE
kvmtop deb reports host cores incorrectly

### ISSUE THREAD

**Issue by flashydave** [cha87de/kvmtop#41]
kvmtop_2.1.2_linux_amd64.deb (with 1 VM running using `kvmtop --cpu --printer=json`) erroneously returns:
`{ "host": {"cpu_cores": 10,"cpu_curfreq": 2153.284888}, "domains": [{"UUID": "ea9e09b7-540a-45e7-9276-0429b6a429e6","name": "debian8","cpu_cores": 2,"cpu_total": 0,"cpu_steal": 0}]}`

kvmtop container (either latest or master) correctly returns:
`{ "host": {"cpu_cores": 32,"cpu_curfreq": 2328.310028}, "domains": [{"UUID": "ea9e09b7-540a-45e7-9276-0429b6a429e6","name": "debian8","cpu_cores": 2,"cpu_total": 0,"cpu_steal": 0}]}`

The host DOES have 32 cores not 10.

I have not been able to build your source code to debug but from the code it looks like parsing /proc/cpuinfo is somehow failing

**Comment by cha87de** [comment]
The reported issue should be fixed in 9cd19ca6ffbe56079486d2c30769610a319fba82 - please update to the version 2.1.3, which contains this bug fix (cf. changelog in https://github.com/cha87de/kvmtop/releases/tag/2.1.3)

**Comment by flashydave** [comment]
confirm fixed
